# Generated by Django 4.1.2 on 2022-10-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_company_advocates_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advocates',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
